
###Login
POST http://localhost:3000/api/login
content-type: application/json

{
  "name":"carlos",
  "password":"3012001"
}

###Register
POST http://localhost:3000/api/auth
content-type: application/json

{
  "name":"ivan",
  "passwordHash":"ivan1219",
  "level":"admin"
}

###get all users
GET http://localhost:3000/api/auth


###get user by id