GET http://localhost:3000/api/materials

###
POST http://localhost:3000/api/materials
content-type: application/json

{
  "nombre": "llanta",
  "precio": "1500",
  "cantidad": "300",
  "descripcion": "3x3",
  "scrap": false,
  "pieza": false
}