GET http://localhost:3000/api/piezas

###
POST http://localhost:3000/api/piezas
Content-Type: application/json

{
    "nombre": "flat",
    "precio": "10",
    "descripcion": "Descripcion de la pieza 1",
    "cantidad": "100"
  },
  