
###Login
POST http://localhost:3000/api/login
content-type: application/json

{
  "name":"carlos",
  "password":"123456"
}

###Register
POST http://localhost:3000/api/auth
content-type: application/json

{
  "name":"carlos",
  "passwordHash":"123456",
  "level":"admin"
}

###get all users
GET http://localhost:3000/api/auth


###get user by id