GET http://localhost:3000/api/productos

###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
  "nombre": "cajon",
  "cantiad": 10,
  "precio": "",
  "descripcion": "Descripcion del producto 1",
  "piezas": []
}

### focus producto
GET http://localhost:3000/api/producto/62a7dcfd4e287b4ba7c653d0